# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc6a3abb3f1f52f956ac7e7670bb5ae95fc5fd25fbce1e368c84ae9a65016b6ec2c3e62d2a36bcaf28e179144563a92f676ad211b3700f87c02a8b3cac912927

test:
  secret_key_base: 8f83fdb3c94fead8d0765ee99d2a7835dc741a7137da483a66b3f4473ff48800ab6a0655f2fe16613e532e8a700c5410965e2d131d5701b4f8bcef601d8e549e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
